version: '3'

services:

  myapp-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_guardians
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=CatChairShowShoe
    ports:
      - 3306:3306
  myapp-main:
    image: andrewem/serviciodecalendarios:prueba
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=springuser
      - DATABASE_PASSWORD=CatChairShowShoe
      - DATABASE_NAME=db_guardians
      - DATABASE_PORT=3306
 