version: '3'

services:

  myapp-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_guardians
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=CatChairShowShoe
    ports:
      - 3306:3306
    volumes:
      - ./sql-scripts/createTables.sql:/docker-entrypoint-initdb.d/createTables.sql
      - ./sql-scripts/populateDoctors.sql:/docker-entrypoint-initdb.d/populateDoctors.sql
      - ./sql-scripts/populateShiftConfigs.sql:/docker-entrypoint-initdb.d/populateShiftConfigs.sql
      - ./sql-scripts/populateAllowedShifts.sql:/docker-entrypoint-initdb.d/populateAllowedShifts.sql
  myapp-main:
    image: andrewem/serviciodecalendarios:prueba
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=springuser
      - DATABASE_PASSWORD=CatChairShowShoe
      - DATABASE_NAME=db_guardians
      - DATABASE_PORT=3306
  db:
    image: postgres
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: "BotGuardianes2021"

  calendar:
    image: tuxnvape/davical-standalone
    volumes:
      - davical_config:/config
    restart: always
    ports:
      - 80:80
    environment:
      HOST_NAME: "guardianes"
      PGSQL_ROOT_PASS: "BotGuardianes2021"
      PASSDAVDB: "BotGuardianes2021"
      DBHOST: "db"
      ADMINDAVICALPASS: "BotGuardianes2021"
      LANG: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
      DAVICAL_LANG: "en_US"
volumes:
  davical_config:
  pgsql_data:
 