FROM ubuntu:18.04
CMD /bin/bash
RUN apt-get update
RUN apt upgrade -y
RUN apt-get install openjdk-8-jdk -y
RUN apt-get install git -y
RUN apt install software-properties-common -y && add-apt-repository ppa:deadsnakes/ppa -y
RUN apt install python3.7 -y
RUN apt-get -y install python3-pip
RUN apt-get install -y gcc
RUN apt-get -y install curl 