/**
 * Contains the repository interfaces used to access the data-source configured.
 * 
 * Note: the actual classes implementing these interfaces will vary depending on
 * the selected data-source. Nevertheless, they will be auto-generated by Jpa.
 * 
 * @author miggoncan
 */
package guardians.model.repositories;